In [28]:
#The code below is a python script to turn the tables into a functioning python dataframe.
from pyspark.sql import SparkSession
import pandas as pd

spark = SparkSession.builder.appName("Sanitized_Refund_Lakehouse").getOrCreate()

df_Recipient_fb = spark.read.table("df_SAN_Recipient_Feedback")
df_Disbursements = spark.read.table("df_SAN_Disbursements")
df_Recipient_Pay = spark.read.table("df_SAN_RecipientPayments")
df_Apartment = spark.read.table("SAN_ApartmentNameRef")

StatementMeta(, 74a85829-2033-4be3-aa0d-6fe3da3887fe, 30, Finished, Available, Finished)

In [29]:
joined_df = df_Disbursements.join(df_Apartment, df_Apartment.ProductId == df_Disbursements.ProductsId, "inner")
joined_df.show()

StatementMeta(, 74a85829-2033-4be3-aa0d-6fe3da3887fe, 31, Finished, Available, Finished)

+---------------+-----------+----------+----------+----------------------+---------------------+------------------+--------------+------------------------+---------------------+--------------------+---------+-----+-------+
|DisbursementsId|EffectiveOn| ExpiresOn|ProductsId|DisbursementStatusName|Revocation_ReasonName|       TotalAmount|num_Recipients|num_RecipientAllocations|DisbursementPartyType|       SanitizedName|ProductId|  Zip|_padZip|
+---------------+-----------+----------+----------+----------------------+---------------------+------------------+--------------+------------------------+---------------------+--------------------+---------+-----+-------+
|         191151| 2024-09-30|2024-10-05|      1481|              Complete|                 NULL|           766.155|             4|                      16|          Multi-Party|Jumping Cholla Woods|     1481| 4011|  04011|
|          49387| 2024-01-26|2024-01-31|      2796|              Complete|                 NULL|          3264.944|             2|                      16|          Multi-Party| Luminous Luxe Lofts|     2796|77025|  77025|
|          34802| 2023-12-22|2023-12-27|      3475|              Complete|                 NULL|          1444.418|             4|                      16|          Multi-Party|California Hoptre...|     3475|29611|  29611|
|         236270| 2024-12-13|2024-12-18|      4559|              Complete|                 NULL|           263.484|             4|                      16|          Multi-Party|Patrol Plaza Resi...|     4559|34741|  34741|
|         193599| 2024-09-27|2024-10-02|      3254|              Complete|                 NULL|             380.0|             4|                      16|          Multi-Party|Southern Bayberry...|     3254|80220|  80220|
|          91079| 2024-04-19|2024-04-24|      4014|              Complete|                 NULL|          3896.672|             2|                      52|          Multi-Party|Anacahuita Apartm...|     4014| 4011|  04011|
|         129600| 2024-07-05|2024-07-10|      4139|              Complete|                 NULL|          2688.016|             2|                      24|          Multi-Party|Florida Cupania A...|     4139| 4011|  04011|
|          26052| 2023-12-13|2023-12-18|      4508|              Complete|                 NULL|2719.9829999999997|             2|                      20|          Multi-Party|            Graytwig|     4508| 4011|  04011|
|          31277| 2023-12-17|2023-12-22|      3007|              Complete|                 NULL|1963.2509999999997|             2|                      18|          Multi-Party| Furry Friends Flats|     3007| 4011|  04011|
|         233553| 2024-12-07|2024-12-12|      1384|              Complete|                 NULL|489.99999999999994|             2|                      14|          Multi-Party|  Hopbush Apartments|     1384|77054|  77054|
|          79022| 2024-03-25|2024-03-30|      4854|              Complete|                 NULL|1400.6399999999999|             2|                      22|          Multi-Party|Texas Ash Apartments|     4854|21204|  21204|
|          12425| 2023-11-12|2023-11-17|      4070|              Complete|                 NULL|             390.0|             2|                      60|          Multi-Party|Ambient Aura Apar...|     4070|40245|  40245|
|          60782| 2024-02-15|2024-02-20|      6010|              Complete|                 NULL|           401.868|             2|                      18|          Multi-Party|     The Studio Spot|     6010| 4011|  04011|
|         133136| 2024-07-06|2024-07-11|      6388|              Complete|                 NULL|           1836.73|             2|                      32|          Multi-Party|      Rainbow Ridges|     6388| 4011|  04011|
|         188701| 2024-09-24|2024-09-29|      3847|              Complete|                 NULL|1026.3780000000002|             4|                      20|          Multi-Party|      Giggle Gardens|     3847|78727|  78727|
|         204134| 2024-10-14|2024-10-19|      4790|              Complete|                 NULL| 5007.674999999999|             5|                      20|          Multi-Party|        Luxury Lofts|     4790| 4011|  04011|
|          31506| 2023-12-19|2023-12-24|      2925|              Complete|                 NULL|           6084.32|             3|                      75|          Multi-Party|Pet-Friendly Pent...|     2925|92626|  92626|
|         127696| 2024-06-28|2024-07-03|      5478|              Complete|                 NULL|           586.606|             5|                      25|          Multi-Party|Florida Anise Tre...|     5478|85281|  85281|
|         103769| 2024-05-17|2024-05-22|      3387|              Complete|                 NULL|           1966.14|             3|                      18|          Multi-Party|       Phoenix Place|     3387| 4011|  04011|
|         189984| 2024-09-26|2024-10-01|      2285|               Expired|                 NULL|2032.6579999999997|             2|                      14|          Multi-Party| Blue Ash Apartments|     2285|90016|  90016|
+---------------+-----------+----------+----------+----------------------+---------------------+------------------+--------------+------------------------+---------------------+--------------------+---------+-----+-------+
only showing top 20 rows

In [47]:
pandas_Joined = joined_df.toPandas()

StatementMeta(, 74a85829-2033-4be3-aa0d-6fe3da3887fe, 49, Finished, Available, Finished)

In [44]:
stats = pandas_Joined.groupby('SanitizedName', as_index=False).agg(Completed=('DisbursementStatusName', lambda x: x.value_counts(normalize=True)['Complete']))

StatementMeta(, 74a85829-2033-4be3-aa0d-6fe3da3887fe, 46, Finished, Available, Finished)

In [48]:
from IPython.display import display
display(stats)
display(pandas_Joined)

StatementMeta(, 74a85829-2033-4be3-aa0d-6fe3da3887fe, 50, Finished, Available, Finished)

                  SanitizedName  Completed
0    Absolute Allure Apartments   0.762712
1             Aerium Apartments   0.820225
2                Aha Apartments   0.722222
3               Airspace Alcove   0.707965
4            Alaska Cedar Place   0.872093
..                          ...        ...
995              Zen Residences   0.553459
996                 Zenith Zone   0.518868
997    Zephyr Zenith Residences   0.710383
998             Zest Residences   0.500000
999   Zestful Zenith Apartments   0.714286

[1000 rows x 2 columns]

,DisbursementsId,EffectiveOn,ExpiresOn,ProductsId,DisbursementStatusName,Revocation_ReasonName,TotalAmount,num_Recipients,num_RecipientAllocations,DisbursementPartyType,SanitizedName,ProductId,Zip,_padZip
0,191151,2024-09-30,2024-10-05,1481,Complete,None,766.155,4,16,Multi-Party,Jumping Cholla Woods,1481,4011,04011
1,49387,2024-01-26,2024-01-31,2796,Complete,None,3264.944,2,16,Multi-Party,Luminous Luxe Lofts,2796,77025,77025
2,34802,2023-12-22,2023-12-27,3475,Complete,None,1444.418,4,16,Multi-Party,California Hoptree Woods,3475,29611,29611
3,236270,2024-12-13,2024-12-18,4559,Complete,None,263.484,4,16,Multi-Party,Patrol Plaza Residences,4559,34741,34741
4,193599,2024-09-27,2024-10-02,3254,Complete,None,380.000,4,16,Multi-Party,Southern Bayberry Woods,3254,80220,80220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131359,35316,2023-12-23,2023-12-28,3557,Complete,None,450.000,1,1,Single-Party,Green Living Lofts,3557,91203,91203
131360,35349,2023-12-23,2023-12-28,3557,Complete,None,450.000,1,1,Single-Party,Green Living Lofts,3557,91203,91203
131361,35305,2023-12-23,2023-12-28,3557,Complete,None,450.000,1,1,Single-Party,Green Living Lofts,3557,91203,91203
131362,35336,2023-12-23,2023-12-28,3557,Complete,None,450.000,1,1,Single-Party,Green Living Lofts,3557,91203,91203
131363,35319,2023-12-23,2023-12-28,3557,Complete,None,450.000,1,1,Single-Party,Green Living Lofts,3557,91203,91203